FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn[standard] \
    opencv-python-headless \
    requests \
    typer \
    pyserial \
    numpy

EXPOSE 8022

CMD ["python", "-m", "uvicorn", "server.video_stream:app", "--host", "0.0.0.0", "--port", "8022"]
